import { Link } from "react-router-dom";
import { PiArrowLeftBold } from "react-icons/pi";
import Aurora from "../components/reactbits/Aurora";
import Button from "../components/ui/Button";
import Logo from "../components/ui/Logo";

export default function NotFound() {
  return (
    <div className="relative flex min-h-dvh flex-col items-center justify-center overflow-hidden px-6 text-center">
      <Aurora intensity={0.7} />
      <div className="relative">
        <Logo className="mb-10" />
        <p className="font-mono text-sm text-brand-400">404</p>
        <h1 className="mt-3 text-3xl font-semibold text-ink-50 sm:text-4xl">
          This page isn't here
        </h1>
        <p className="mx-auto mt-3 max-w-sm text-[0.9375rem] leading-relaxed text-ink-400">
          The link may have been regenerated by its owner, or it never existed.
        </p>
        <Link to="/" className="mt-8 inline-block">
          <Button icon={PiArrowLeftBold} variant="secondary">
            Back home
          </Button>
        </Link>
      </div>
    </div>
  );
}
